// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

public interface PersonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Person)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 age = 3;</code>
   * @return The age.
   */
  int getAge();

  /**
   * <code>repeated int32 nums = 4;</code>
   * @return A list containing the nums.
   */
  java.util.List<java.lang.Integer> getNumsList();
  /**
   * <code>repeated int32 nums = 4;</code>
   * @return The count of nums.
   */
  int getNumsCount();
  /**
   * <code>repeated int32 nums = 4;</code>
   * @param index The index of the element to return.
   * @return The nums at the given index.
   */
  int getNums(int index);

  /**
   * <code>repeated int32 integers = 5;</code>
   * @return A list containing the integers.
   */
  java.util.List<java.lang.Integer> getIntegersList();
  /**
   * <code>repeated int32 integers = 5;</code>
   * @return The count of integers.
   */
  int getIntegersCount();
  /**
   * <code>repeated int32 integers = 5;</code>
   * @param index The index of the element to return.
   * @return The integers at the given index.
   */
  int getIntegers(int index);

  /**
   * <code>uint64 timestamp = 7;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <code>.Address address = 8;</code>
   * @return Whether the address field is set.
   */
  boolean hasAddress();
  /**
   * <code>.Address address = 8;</code>
   * @return The address.
   */
  Address getAddress();
  /**
   * <code>.Address address = 8;</code>
   */
  AddressOrBuilder getAddressOrBuilder();
}
